# User config
author: "✨ HBD ✨"
tagline: "Website buat ngucapin hbd"
description: "Happy belated birthday 🎉🤩, you know i always hoping the best for you 😬. sorry if it taking so long 😣"
keywords: "Happy, Happy Birthday, Birthday"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/portofolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
